### ISSUE TITLE
CEWP is js instead of .txt file?

### ISSUE THREAD

**Issue by pvestal** [mrackley/HillbillyTabs-4.0#2]
Is the HillbillyTabs.4.CEWP.js supposed to be a txt file or a js file?

**Comment by mrackley** [comment]
For future reference for those curious. It truly doesn't matter what the extension is for the HillbillyTabs.4.CEWP file. I use .js so that I get syntax highlighting. If you use .txt you don't get that. If you use .html then you can't open it to edit it in the new modern text editor. 
The file extension does not affect how a Content Editor Web part loads the file.
